# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "主页"
  url = ''
  weight = 10

[[main]]
  name = "研究内容"
  url = "#research"
  weight = 20
  identifier = "research"

[[main]]
  name = "成员"
  url = "#people"
  weight = 30

[[main]]
  name = "论文"
  url = "/publication/"
  weight = 40

[[main]]
  name = "资源"
  url = "/resrouces/"
  weight = 50
  identifier = "Resources"

[[main]]
  name = "科研设备"
  url = "/resources/facilities"
  weight = 10
  parent = "Resources"

[[main]]
  name = "研究赞助"
  url = "/resources/sponsors"
  weight = 20
  parent = "Resources"

[[main]]
  name = "新闻"
  url = "/news/"
  weight = 60

[[main]]
  name = "联系"
  url = "#contact"
  weight = 70
