# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ''
  weight = 10

[[main]]
  name = "Research"
  url = "#research"
  weight = 20
  identifier = "research"

[[main]]
  name = "People"
  url = "#people"
  weight = 30

[[main]]
  name = "Publication"
  url = "/publication/"
  weight = 40

[[main]]
  name = "Resources"
  url = "/resrouces/"
  weight = 50
  identifier = "Resources"

[[main]]
  name = "Facilities"
  url = "/resources/facilities"
  weight = 50
  parent = "Resources"

[[main]]
  name = "Research Sponsors"
  url = "/resources/sponsors"
  weight = 50
  parent = "Resources"

[[main]]
  name = "News"
  url = "/news/"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70
